project:
  type: website
  output-dir: docs
  preview:
    port: 4205
    browser: false
  resources: 
    - env.yaml
    - "*.ipynb"
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!scripts/"
    - "!README.md"
    - "env.yaml"

bibliography: references.bib

lang: en

website:
  title: "The bbob test suite"
  open-graph: true
  favicon: "images/favicon.png"
  navbar:
    title: false
    background: primary
    logo: images/favicon.png
  sidebar:
    style: "docked"
    contents:
      - section: "BBOB"
        contents:
          - text: "Function Definitions"
            href: "bbob/def.html"
          - text: "Visualizations"
            href: "bbob/vis.html"
      - section: "Mixed-integer"
        contents:
          - text: "Function Definitions"
            href: "mixed-integer/def.html"
          - text: "Visualizations"
            href: "mixed-integer/vis.html"
  search: 
    location: navbar
    type: overlay

format:
  html:
    toc: true
    toc-depth: 2
    theme: coco.scss
    css: "assets/css/custom.css"
    html-math-method: katex
    code-copy: true
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: ".*numbbo\/bbob-plots.*"
    grid:
      sidebar-width: 250px
      body-width: 1500px
      margin-width: 250px
      gutter-width: 1.5rem

